language: cpp

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

matrix:
  exclude:
    - os: osx
      compiler: gcc

before_install: source build_tools/travis/before_install.sh

install: source build_tools/travis/install.sh

script:
  - $CXX --version
  - make test-OpenMEEG
  - cpack -G TGZ .
  - echo "$SSH_KEY" > toto.txt
  - cat toto.txt
  - sshpass -p '$DEPLOY_PASSWORD' scp *tar.gz $DEPLOY_LOGIN@scm.gforge.inria.fr:/home/groups/openmeeg/htdocs/download/
